version: '3.1'

services:
  frontend:
    build: front/
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    depends_on:
      - backend
    networks:
      - tpNetwork


  backend:
    build: api/
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./api:/usr/src/app
    networks:
      - tpNetwork

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tpNetwork

networks:
  tpNetwork:

volumes:
  mongodb_data:
