version: '3.1'

services:
  frontend:
    build: front/
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    depends_on:
      - backend
      - database
    networks:
      - tpNetwork


  backend:
    build: api/
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on:
      - database
    networks:
      - tpNetwork

  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tpNetwork

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tpNetwork
    depends_on:
      - frontend
      - backend
      - database

networks:
  tpNetwork:

volumes:
  mongodb_data:
